flowchart TD
subgraph 音楽ゲームのフローチャート
    
    Start(開始)
    MainMenu(メインメニュー)
    GameSelect(ゲーム選択)
    RhythmGame(リズムゲーム)
    ActionGame(アクションゲーム)
    ModeSelect[モード選択]
    MusicSelect(曲選択)
    PlayStart(演奏)
    PlayEnd[曲終了?]
    H(結果表示)
    I(スコア保存)
    J[ランキング更新?]
    K(新しいランキング表示)
    L(終了)
    
    Start --> MainMenu
    MainMenu --> GameSelect
    GameSelect --> RhythmGame
    GameSelect --> ActionGame
    RhythmGame --> ModeSelect
    ModeSelect -->|シングルプレイ| MusicSelect
    ModeSelect -->|マルチプレイ| PlayStart
    PlayStart --> PlayEnd
    PlayEnd -->|はい| H
    PlayEnd -->|いいえ| PlayStart
    H --> I
    I --> J
    J -->|はい| K
    J -->|いいえ| L
    
    
end

