@startuml

' クラスの定義
class Player {
    +Move()
    +Attack()
    +Jump()
}

interface IInput {
    +Move()
    +Attack()
    +Jump()    
}
interface IMove {
    +Move()
}
interface IAttack {
    +Attack()
}
interface IJump {
    +Jump()
}

interface IPlayer {
    +Move()
    +Attack()
    +Jump()
}

@enduml
